apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: Web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: dashboard
        image: imagename

